# Generated by Django 5.0.2 on 2024-02-17 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friendrequest_userfriends_usernotifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfriends',
            name='friends',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_to', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
