# Generated by Django 5.0.2 on 2024-02-21 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_botconversations_botusermessage_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouproomprofile',
            name='room_bot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.collection'),
        ),
    ]
