# Generated by Django 5.0.2 on 2024-02-13 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='message',
        ),
    ]
