# Generated by Django 5.0.2 on 2024-02-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_privatemessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
