# Generated by Django 5.0.2 on 2024-02-13 13:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_privaterooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privaterooms',
            name='room_name',
            field=models.UUIDField(default=uuid.UUID('143ce13e-408f-45eb-9d57-0684368522e4'), unique=True),
        ),
    ]
