# Generated by Django 5.0.2 on 2024-02-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='document_folder_name',
            field=models.CharField(max_length=1000),
        ),
    ]
