# Generated by Django 5.0.2 on 2024-02-25 01:34

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_datasource_document_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='file',
            field=models.FileField(max_length=1000, upload_to=chat.models.get_upload_path),
        ),
    ]
