# Generated by Django 5.0.2 on 2024-02-13 16:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_privaterooms_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privaterooms',
            name='room_name',
            field=models.UUIDField(default=uuid.UUID('00a658fe-0c96-4695-8c65-707c26a2efc4'), unique=True),
        ),
    ]
