# Generated by Django 5.0.2 on 2024-02-13 17:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_privaterooms_room_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatemessage',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='privaterooms',
            name='room_name',
            field=models.UUIDField(default=uuid.UUID('5a23e9a1-159e-4bd7-9de0-5bbf4d454296'), unique=True),
        ),
    ]
