# Generated by Django 5.0.2 on 2024-02-15 03:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_privaterooms_room_name_collection_datasource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privaterooms',
            name='room_name',
            field=models.UUIDField(default=uuid.UUID('cdee29f5-efe0-4741-87ef-cc9805503ca0'), unique=True),
        ),
    ]
