# Generated by Django 5.0.2 on 2024-02-15 21:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_room_creator_room_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='online',
            new_name='members',
        ),
        migrations.AddField(
            model_name='room',
            name='room_bot',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.collection'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_title_caption',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='privaterooms',
            name='room_name',
            field=models.UUIDField(default=uuid.UUID('f292751f-0ede-4ea2-b54b-2e2c2840d778'), unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.UUIDField(default=uuid.UUID('aa58b8e3-0459-492e-bdcc-6008aee9e584')),
        ),
    ]
